### ISSUE TITLE
Just wanna say: thank you

### ISSUE THREAD

**Issue by nitram509** [kanimaru/fritzbox-soap-example#2]
Hi Kani,

I just wanna say thank you.
Your example code, did help me understand the authentication schema.
Also, I did go one step further and implemented a comprehensive library for the TR064 API,
see https://github.com/nitram509/gofritz.

Cheers and Merry Christmas.
Martin

PS: this issue can be closed.

**Comment by kanimaru** [comment]
Merry Christmas to you too. I'm happy to help you with this meh library :)
